[package]
name = "provenix-cli"
version = "0.1.0"
edition = "2021"
description = "Integrated CLI for Provenix (px / provenix)"

[[bin]]
name = "px"
path = "src/main.rs"

[dependencies]
provenix-corelib = { path = "../corelib" }
provenix-sbom = { path = "../sbom" }
provenix-attest = { path = "../attest" }
provenix-utils = { path = "../utils" }
