[package]
name = "provenix-attest"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "provenix_attest"
path = "src/lib.rs"

[[bin]]
name = "pxa"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }

# Internal dependencies
provenix-core = { path = "../provenix-core" }
provenix-plugin = { path = "../provenix-plugin" }
provenix-utils = { path = "../provenix-utils" }

# External dependencies
ctor = "0.2"
sha2 = "0.10"
chrono = "0.4"

# crate-specific deps
[target.'cfg(unix)'.dependencies]
# add platform specific if needed
